package com.mangala.showroom.model;

public enum OrderStatus {
    PENDING_PAYMENT,
    PAYMENT_VERIFICATION_IN_PROGRESS,
    ORDER_CONFIRMED,
    PROCESSING,
    PACKED,
    READY_FOR_DISPATCH,
    HANDED_OVER_TO_SHIPPING,
    IN_TRANSIT,
    ARRIVED_AT_REGIONAL_HUB,
    OUT_FOR_DELIVERY,
    DELIVERED,
    DELIVERY_DELAYED,
    CANCELLED
}
